# Generated by Django 4.2.4 on 2023-10-16 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0004_task_worker_alter_task_owner_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner_task",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Заказчик",
            ),
        ),
    ]
