# Generated by Django 4.2.4 on 2023-10-16 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_alter_task_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Созданное время"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Обновленное время"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "point",
                    models.CharField(
                        choices=[
                            ("a", "А"),
                            ("b", "Б"),
                            ("v", "В"),
                            ("g", "Г"),
                            ("d", "Д"),
                            ("e", "Е"),
                            ("j", "Ж"),
                            ("z", "З"),
                            ("i", "И"),
                            ("k", "К"),
                            ("l", "Л"),
                        ],
                        default="a",
                        verbose_name="Точка",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address",
                        to="tasks.task",
                        verbose_name="Задание",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="taskaddress",
            constraint=models.UniqueConstraint(
                fields=("task", "point"), name="unique_task_point"
            ),
        ),
    ]
