# Generated by Django 4.2.4 on 2023-10-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0006_taskaddress_taskaddress_unique_task_point"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskaddress",
            options={"verbose_name": "Адрес", "verbose_name_plural": "Адреса"},
        ),
        migrations.AlterModelOptions(
            name="taskimage",
            options={"verbose_name": "Фото", "verbose_name_plural": "Фото"},
        ),
        migrations.AlterModelOptions(
            name="taskresponse",
            options={"verbose_name": "Отклик", "verbose_name_plural": "Отклик"},
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Открыто"),
                    ("in_progress", "Выполняется"),
                    ("completed", "Выполнено"),
                    ("not_completed", "Не выполнено"),
                    ("closed", "Закрыто"),
                ],
                default="open",
                max_length=15,
            ),
        ),
    ]
