# Generated by Django 4.2.4 on 2023-10-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0007_alter_taskaddress_options_alter_taskimage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskresponse",
            name="response_type",
            field=models.CharField(
                choices=[
                    ("plain", "Обычный"),
                    ("base", "Базовый"),
                    ("unlim", "Безлимитный"),
                    ("post", "Постоплата"),
                ],
                default=1,
                verbose_name="Тип отклика",
            ),
            preserve_default=False,
        ),
    ]
