# Generated by Django 4.2.4 on 2023-10-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0008_taskresponse_response_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskresponse",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Рассматриваемый"),
                    ("accepted", "Принято"),
                    ("rejected", "Отказано"),
                ],
                default="pending",
                max_length=12,
                verbose_name="СТАТУС",
            ),
        ),
    ]
