# Generated by Django 4.2.4 on 2023-11-06 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0009_alter_taskresponse_status"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="taskaddress",
            name="unique_task_point",
        ),
    ]
