# Generated by Django 4.2.4 on 2023-11-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0010_remove_taskaddress_unique_task_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_business",
            field=models.BooleanField(default=False, verbose_name="Бизнес-задание"),
        ),
        migrations.AddField(
            model_name="task",
            name="is_remote",
            field=models.BooleanField(default=False, verbose_name="Удалённо"),
        ),
        migrations.AddField(
            model_name="task",
            name="private_information",
            field=models.TextField(blank=True, null=True, verbose_name="Приватная инфомация"),
        ),
    ]
