# Generated by Django 4.2.4 on 2023-11-25 11:22

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0011_task_is_business_task_is_remote_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskaddress",
            name="coords",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326, verbose_name="Координата"
            ),
        ),
    ]
