version: '3'

volumes:
  postgres_data: {}
  postgres_data_backups: {}
  django_media: {}
  django_static: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: profis_django
    volumes:
      - django_media:/app/profis/media
      - django_static:/app/profis/staticfiles
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: profis_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: profis_nginx
    depends_on:
      - django
    volumes:
      - django_media:/usr/share/nginx/media:ro
      - django_media:/usr/share/nginx/staticfiles:ro

  redis:
    image: redis:6

  celeryworker:
    <<: *django
    image: profis_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: profis_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: profis_production_flower
    ports:
      - '5555:5555'
    command: /start-flower
