# Generated by Django 4.2.4 on 2023-09-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_name_user_first_name_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars", verbose_name="Фото профиля"),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, null=True, verbose_name="Опыт, навыки и преимущества"),
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True, choices=[("m", "Мужчина"), ("f", "Женщина")], null=True, verbose_name="Пол"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_worker",
            field=models.BooleanField(default=False, verbose_name="Исполнитель"),
        ),
        migrations.AddField(
            model_name="user",
            name="number_of_views",
            field=models.PositiveIntegerField(default=0, verbose_name="Просмотры"),
        ),
        migrations.AddField(
            model_name="user",
            name="work_experiance",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Стаж работы"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=64, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=64, verbose_name="Фамилия"),
        ),
    ]
