# Generated by Django 4.2.4 on 2023-09-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_avatar_user_bio_user_date_of_birth_user_gender_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Пользователь", "verbose_name_plural": "Пользователи"},
        ),
        migrations.AlterField(
            model_name="user",
            name="is_worker",
            field=models.BooleanField(default=False, verbose_name="Статус исполнителя"),
        ),
    ]
