# Generated by Django 4.2.4 on 2023-09-24 16:27

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_userwallet"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userwallet",
            options={"verbose_name": "Кошелек пользователя", "verbose_name_plural": "Кошелек пользователя"},
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None, unique=True, verbose_name="Номер телефона"
            ),
        ),
    ]
