# Generated by Django 4.2.4 on 2023-10-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0003_alter_category_options_category_order"),
        ("users", "0007_alter_userwallet_options_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="categories",
            field=models.ManyToManyField(
                related_name="user_category",
                to="categories.category",
                verbose_name="Категории",
            ),
        ),
    ]
