# Generated by Django 4.2.4 on 2023-11-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name="Email"),
        ),
    ]
