# Generated by Django 4.2.4 on 2023-12-26 07:41

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_user__id_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_seen",
            field=models.DateTimeField(null=True, verbose_name="Последний визит"),
        ),
        migrations.AddField(
            model_name="user",
            name="online_status",
            field=models.SmallIntegerField(default=0, verbose_name="Онлайн статус"),
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                error_messages={"unique": "Имя пользователя уже занято."},
                max_length=150,
                null=True,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
