# Generated by Django 4.2.4 on 2023-09-20 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="category",
                validators=[django.core.validators.FileExtensionValidator(["svg", "png"])],
                verbose_name="Иконка",
            ),
        ),
    ]
