# Generated by Django 4.2.4 on 2023-10-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0003_alter_category_options_category_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=9, verbose_name="Цена"
            ),
        ),
    ]
