# Generated by Django 4.2.4 on 2023-10-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0004_category_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="base_price_100",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=9,
                verbose_name="Цена пакета за 25 откликов",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="base_price_25",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=9,
                verbose_name="Цена пакета за 25 откликов",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="base_price_50",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=9,
                verbose_name="Цена пакета за 25 откликов",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="unlim_price_15",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=9,
                verbose_name="Цена пакета на 15 дней",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="unlim_price_30",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=9,
                verbose_name="Цена пакета на 30 дней",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="unlim_price_90",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=9,
                verbose_name="Цена пакета на 90 дней",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=9,
                verbose_name="Цена за 1 отклик",
            ),
        ),
    ]
