# Generated by Django 4.2.4 on 2023-10-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0005_category_base_price_100_category_base_price_25_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="post_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=9,
                verbose_name="Цена после оплаты",
            ),
        ),
    ]
