# Generated by Django 4.2.4 on 2023-10-05 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0004_task_worker_alter_task_owner_alter_task_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskRating",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Созданное время")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновленное время")),
                ("quality", models.PositiveSmallIntegerField(default=0, verbose_name="Качество")),
                ("politeness", models.PositiveSmallIntegerField(default=0, verbose_name="Вежливость")),
                ("punctuality", models.PositiveSmallIntegerField(default=0, verbose_name="Пунктуальность")),
                ("adequacy", models.PositiveSmallIntegerField(default=0, verbose_name="Адекватность")),
                ("cost_of_services", models.PositiveSmallIntegerField(default=0, verbose_name="Стоимость услуг")),
                ("review", models.TextField(verbose_name="Отзыв")),
                (
                    "orderer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_as_orderer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Заказчик",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.task", verbose_name="Задание"
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_as_worker",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Исполнитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рейтинг",
                "verbose_name_plural": "Рейтинги",
            },
        ),
    ]
