# Generated by Django 4.2.4 on 2023-11-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0002_taskrating_unique_worker_rating_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskrating",
            name="adequacy",
        ),
        migrations.RemoveField(
            model_name="taskrating",
            name="cost_of_services",
        ),
        migrations.RemoveField(
            model_name="taskrating",
            name="politeness",
        ),
        migrations.RemoveField(
            model_name="taskrating",
            name="punctuality",
        ),
        migrations.RemoveField(
            model_name="taskrating",
            name="quality",
        ),
        migrations.AddField(
            model_name="taskrating",
            name="score",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Балл"),
        ),
    ]
