# Generated by Django 4.2.4 on 2023-10-31 08:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Созданное время')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновленное время')),
                ('chat_name', models.CharField(max_length=64, unique=True, verbose_name='')),
                ('participants', models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Созданное время')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновленное время')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('file', models.FileField(blank=True, null=True, upload_to='files', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpeg', 'jpg', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt'])], verbose_name='Файл')),
                ('is_seen', models.BooleanField(default=False)),
                ('participants', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='chats.chat')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
