# Generated by Django 4.2.4 on 2023-12-01 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Созданное время")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновленное время")),
                ("object_id", models.PositiveIntegerField()),
                ("message", models.TextField(verbose_name="Текст")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("message", "Message"),
                            ("response", "Response"),
                            ("broadcast", "Broadcast"),
                            ("feedback", "Feedback"),
                        ],
                        default="broadcast",
                        verbose_name="Тип нотификации",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Созданное время")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновленное время")),
                ("is_read", models.BooleanField(default=False)),
                (
                    "notification",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="notifications.notification"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ManyToManyField(through="notifications.UserNotification", to=settings.AUTH_USER_MODEL),
        ),
    ]
