# Generated by Django 4.2.4 on 2023-12-02 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usernotification",
            name="notification",
        ),
        migrations.RemoveField(
            model_name="usernotification",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={"verbose_name": "Нотификации", "verbose_name_plural": "Нотификации"},
        ),
        migrations.AddField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("message", "Message"),
                    ("response", "Response"),
                    ("broadcast", "Broadcast"),
                    ("feedback", "Feedback"),
                    ("transaction", "Transaction"),
                    ("subscribtion", "Subscribtion"),
                ],
                default="broadcast",
                verbose_name="Тип нотификации",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="notification",
            name="user",
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["content_type", "object_id"], name="notificatio_content_702c56_idx"),
        ),
        migrations.DeleteModel(
            name="UserNotification",
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
