# Generated by Django 4.2.4 on 2023-10-18 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Созданное время")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновленное время")),
                ("name", models.CharField(max_length=255, verbose_name="")),
                ("description", models.CharField(max_length=1024, verbose_name="")),
                (
                    "plan_type",
                    models.CharField(choices=[("unlim", "Безлимитный"), ("base", "Базовый")], verbose_name=""),
                ),
            ],
            options={
                "verbose_name": "Тариф",
                "verbose_name_plural": "Тарифы",
            },
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Созданное время")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновленное время")),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("discount", models.PositiveSmallIntegerField(default=0, verbose_name="Скидка")),
                ("duration", models.PositiveSmallIntegerField(default=0, verbose_name="Дни")),
                ("max_responses", models.PositiveSmallIntegerField(default=0, verbose_name="Количество откликов")),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="subscription.plan", verbose_name="Тариф"
                    ),
                ),
            ],
            options={
                "verbose_name": "Пакет",
                "verbose_name_plural": "Пакеты",
            },
        ),
    ]
