# Generated by Django 4.2.4 on 2023-10-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "subscription",
            "0003_userplan_number_of_responses_userplan_package_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userplan",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=9, verbose_name="Общая сумма"
            ),
        ),
    ]
